### ISSUE TITLE
Viikko2, NHL Statistics -tehtävän .pom vailla versiota

### ISSUE THREAD

**Issue by basic-ohjelmoia** [mluukkai/ohtu2016#129]
Hei,

Viikon 2 NHL Statistics -tehtävän pom-fileestä puuttuu näköjään version-parametri. Tunkee Windowsin Netbeansin konsoliin mojovat varoitukset ilman Maven-pluginin versiomäärittelyä:

Some problems were encountered while building the effective model for wad:Ohtu-NhlStatistics1:jar:1.0-SNAPSHOT
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 28, column 21
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.

https://github.com/mluukkai/ohtu2016/blob/master/viikko2/Ohtu-NhlStatistics1/pom.xml#L29

Lisäämällä pelkän rivin:
<version>3.5.1</version>
varoitus poistuu.
- TH

**Comment by mluukkai** [comment]
Korjattu.
